name: laravel-app

services:
  app:
    build:
      context: .
      dockerfile: infra/docker/php/Dockerfile
    container_name: laravel-app-php
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      # Xdebug
      - XDEBUG_MODE=debug,develop
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=yes
    depends_on:
      - db
    networks:
      - laravel

  web:
    build:
      context: .
      dockerfile: infra/docker/nginx/Dockerfile
    container_name: laravel-app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

  node:
    image: node:18-alpine
    container_name: laravel-app-node
    working_dir: /var/www/html
    command: sh -c "npm ci && npm run build && ls -la /var/www/html/public/build || true && tail -f /dev/null"
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-app-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
    driver: bridge
